### ISSUE TITLE
orxporter crashes when trying to concatenate %z with a folder name

### ISSUE THREAD

**Issue by dzuk-mutant** [mutantstandard/orxporter#27]
The output given by %z doesn't appear to be a string and Python will crash when trying to concatenate it with a string as part of the output.
```
Exporting 7564 emoji...
- -l
- to 'out/final/font_sources/png-%z/%u'
- 4 threads
 |                                | 0 / 7564 (0:00:02)x∆∆x Thread 0 failed: can only concatenate str (not "type") to str

Traceback (most recent call last):
  File "./orxporter/orxport.py", line 286, in <module>
    main()
  File "./orxporter/orxport.py", line 279, in main
    raise e  # TEMP: for developer stuff
  File "./orxporter/orxport.py", line 265, in main
    license_enabled, cache)
  File "/Users/Dzuk/Work/Main/Mutant Standard/Production Emoji/Emoji/mutant-standard-master/build/orxporter/export.py", line 61, in export
    renderer, license_enabled, cache)
  File "/Users/Dzuk/Work/Main/Mutant Standard/Production Emoji/Emoji/mutant-standard-master/build/orxporter/export.py", line 141, in export_step
    raise ValueError(f'Thread {t.name} failed: {t.err}')
ValueError: Thread 0 failed: can only concatenate str (not "type") to str
```

**Comment by dzuk-mutant** [comment]
This wasn't a bug, just a mistake on my part with the script I used. It was badly formed.
